relativeURLs  = true
#uglyurls      = true

baseURL = "/"

#[languages]
#[languages.en]
#baseURL = "https://example.com/hugo/en"
#
#[languages.no]
#baseURL = "https://example.com/hugo/no"
[params]
enableGitInfoProject = false
enablegetJSON        = false
