baseURL = "https://it-gro.github.io/HugoTemplateCodePlyGnd"
title   = "Hugo Template Codeing Playground"

disablePathToLower = true
DefaultContentLanguage = "en"

# This is for examples/variables/git
enableGitInfo          = true

# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# This is for examples/variables/site/
Copyright       = "demo site vars (c)"
DisqusShortname = "demo site vars (disqus)"
GoogleAnalytics = "demo site vars (google)"
LanguageCode    = "demo site vars (lang code)"
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[taxonomies]
  tag      = "tags"
  category = "categories"
  country  = "countries"

[params]
  #traceFlags = "layout-name:baseof"
  #debug      = true

  enableGitInfoProject = true

  #w3cssColorTheme = "css/w3-theme-custom.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-amber.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-black.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-blue-grey.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-blue.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-brown.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-cyan.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-dark-grey.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-deep-orange.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-deep-purple.css"
  w3cssColorTheme  = "vendor/w3css/4/w3-theme-green.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-grey.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-indigo.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-khaki.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-light-blue.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-light-green.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-lime.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-orange.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-pink.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-purple.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-red.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-teal.css"
  #w3cssColorTheme = "vendor/w3css/4/w3-theme-yellow.css"

  fileLinkCntPerHalf = 15


# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# This is for examples/variables/site/
[Author.jon]
  Name = "Jon Doe"
  anything = "Mr. foo"

[Author.jane]
  Name = "Jane Wild"
  anything = "Zoo"

[social]
  facebook        = "me.42"
  facebook_admin  = ""
  facebook_app_id = "1234"

[permalinks]
  post = "/:year/:month/:title/"

[menu]
[[menu.main]]
  weight = 1
  name   = "Home"
  title  = "Base"
  url    = "/index.html"
  pre    = "fas fa-home"
[[menu.main]]
  weight = 2
  name   = "Contact"
  title  = "Touch"
  url    = "/contact"
  pre    = "far fa-address-card"
[[menu.anything]]
  weight = 1
  name   = "foo"
  title  = "bar"
  url    = "/"
  pre    = ""

[params.anything]
 foo = "bar"
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


#[languages]
#[languages.en]
#baseURL = "https://it-gro.github.io/HugoTemplatingPlayground/en"
#languageName = "English"
#weight = 1
#title = "Hugo Templating Playground"
#
#[languages.no]
#baseURL = "https://it-gro.github.io/HugoTemplatingPlayground/no"
#languageName = "Norsk"
#weight = 2
#title = "Hugo Templating lekeplass"
